name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build with qmake
        run: |
          qmake
          nmake

      - name: Create zip
        run: |
          powershell Compress-Archive -Path release\* -DestinationPath release.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 